# version: '3.8'

# services:
#   db:
#     image: postgres
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: admin
#     ports:
#       - "5432:5432"
#     volumes:
#       - dbdata:/var/lib/postgresql/data
#   app:
#     build: .
#     ports:
#       - "4000:2000"
#     depends_on:
#       - db
# volumes:
#   dbdata:




version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  app:
    image: data_entry-app
    ports:
      - "4000:2000"
    depends_on:
      - db
volumes:
  dbdata: