module.exports = [
 {
  zone: 1,
  category: "LH MAIN BODY",
  sub_category: "A-PILLAR",
  top_position: 20,
  bottom_position: 0,
  right_position: 0,
  left_position: 29,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 2,
  category: "LH MAIN BODY",
  sub_category: "A-PILLAR",
  top_position: 19,
  bottom_position: 0,
  right_position: 0,
  left_position: 39,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 3,
  category: "LH MAIN BODY",
  sub_category: "A-PILLAR",
  top_position: 39,
  bottom_position: 0,
  right_position: 0,
  left_position: 26,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 4,
  category: "LH MAIN BODY",
  sub_category: "A-PILLAR",
  top_position: 58,
  bottom_position: 0,
  right_position: 0,
  left_position: 26,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 38,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "FENDER",
  top_position: 14,
  bottom_position: 0,
  right_position: 0,
  left_position: 44,
  width: 5,
  top_padding: 8,
  bottom_padding: 10,
  right_padding: 7,
  left_padding: 7,
 },
 {
  zone: 5,
  category: "LH MAIN BODY",
  sub_category: "B-PILLAR",
  top_position: 21,
  bottom_position: 0,
  right_position: 0,
  left_position: 42,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 6,
  category: "LH MAIN BODY",
  sub_category: "B-PILLAR",
  top_position: 41,
  bottom_position: 0,
  right_position: 0,
  left_position: 42,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 7,
  category: "LH MAIN BODY",
  sub_category: "B-PILLAR",
  top_position: 59,
  bottom_position: 0,
  right_position: 0,
  left_position: 42,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 8,
  category: "LH MAIN BODY",
  sub_category: "BACK DOOR OPENING",
  top_position: 0,
  bottom_position: 0,
  right_position: 0,
  left_position: 31,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 10,
  left_padding: 10,
 },
 {
  zone: 9,
  category: "LH MAIN BODY",
  sub_category: "BACK DOOR OPENING",
  top_position: 0,
  bottom_position: 0,
  right_position: 0,
  left_position: 51,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 10,
  left_padding: 10,
 },
 {
  zone: 10,
  category: "LH MAIN BODY",
  sub_category: "BACK DOOR OPENING",
  top_position: 19,
  bottom_position: 0,
  right_position: 0,
  left_position: 23,
  width: 5,
  top_padding: 10,
  bottom_padding: 15,
  right_padding: 7,
  left_padding: 6,
 },
 {
  zone: 11,
  category: "LH MAIN BODY",
  sub_category: "BACK DOOR OPENING",
  top_position: 19,
  bottom_position: 0,
  right_position: 0,
  left_position: 66,
  width: 5,
  top_padding: 10,
  bottom_padding: 15,
  right_padding: 6,
  left_padding: 6,
 },
 {
  zone: 12,
  category: "LH MAIN BODY",
  sub_category: "BACK DOOR OPENING",
  top_position: 71,
  bottom_position: 0,
  right_position: 0,
  left_position: 36,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 15,
  left_padding: 15,
 },
 {
  zone: 13,
  category: "LH MAIN BODY",
  sub_category: "C-PILLAR",
  top_position: 26,
  bottom_position: 0,
  right_position: 0,
  left_position: 55,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 14,
  category: "LH MAIN BODY",
  sub_category: "C-PILLAR",
  top_position: 46,
  bottom_position: 0,
  right_position: 0,
  left_position: 55,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 15,
  category: "LH MAIN BODY",
  sub_category: "COWL",
  top_position: 9,
  bottom_position: 0,
  right_position: 0,
  left_position: 25,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 12,
  left_padding: 12,
 },
 {
  zone: 16,
  category: "LH MAIN BODY",
  sub_category: "COWL",
  top_position: 9,
  bottom_position: 0,
  right_position: 0,
  left_position: 49,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 10,
  left_padding: 10,
 },
 {
  zone: 17,
  category: "LH MAIN BODY",
  sub_category: "FRONT DOOR OPENING",
  top_position: 18,
  bottom_position: 0,
  right_position: 0,
  left_position: 35,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 18,
  category: "LH MAIN BODY",
  sub_category: "FRONT DOOR OPENING",
  top_position: 38,
  bottom_position: 0,
  right_position: 0,
  left_position: 26,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 19,
  category: "LH MAIN BODY",
  sub_category: "FRONT DOOR OPENING",
  top_position: 60,
  bottom_position: 0,
  right_position: 0,
  left_position: 29,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 20,
  category: "LH MAIN BODY",
  sub_category: "FRONT DOOR OPENING",
  top_position: 38,
  bottom_position: 0,
  right_position: 0,
  left_position: 41,
  width: 5,
  top_padding: 6,
  bottom_padding: 9,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 21,
  category: "LH MAIN BODY",
  sub_category: "QUARTER",
  top_position: 18,
  bottom_position: 0,
  right_position: 0,
  left_position: 53,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 22,
  category: "LH MAIN BODY",
  sub_category: "QUARTER",
  top_position: 39,
  bottom_position: 0,
  right_position: 0,
  left_position: 54,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 23,
  category: "LH MAIN BODY",
  sub_category: "QUARTER",
  top_position: 32,
  bottom_position: 0,
  right_position: 0,
  left_position: 69,
  width: 5,
  top_padding: 6,
  bottom_padding: 9,
  right_padding: 4,
  left_padding: 3,
 },
 {
  zone: 24,
  category: "LH MAIN BODY",
  sub_category: "REAR DOOR OPENING",
  top_position: 15,
  bottom_position: 0,
  right_position: 0,
  left_position: 48,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 25,
  category: "LH MAIN BODY",
  sub_category: "REAR DOOR OPENING",
  top_position: 29,
  bottom_position: 0,
  right_position: 0,
  left_position: 41,
  width: 5,
  top_padding: 8,
  bottom_padding: 11,
  right_padding: 4,
  left_padding: 4,
 },
 {
  zone: 26,
  category: "LH MAIN BODY",
  sub_category: "REAR DOOR OPENING",
  top_position: 33,
  bottom_position: 0,
  right_position: 0,
  left_position: 56,
  width: 5,
  top_padding: 7,
  bottom_padding: 10,
  right_padding: 3,
  left_padding: 3,
 },
 {
  zone: 27,
  category: "LH MAIN BODY",
  sub_category: "ROCKER PANEL SIDE",
  top_position: 64,
  bottom_position: 0,
  right_position: 0,
  left_position: 29,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 28,
  category: "LH MAIN BODY",
  sub_category: "ROCKER PANEL SIDE",
  top_position: 64,
  bottom_position: 0,
  right_position: 0,
  left_position: 45,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 7,
  left_padding: 7,
 },
 {
  zone: 29,
  category: "LH MAIN BODY",
  sub_category: "ROOF SIDE",
  top_position: 17,
  bottom_position: 0,
  right_position: 0,
  left_position: 34,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 10,
  left_padding: 10,
 },
 {
  zone: 30,
  category: "LH MAIN BODY",
  sub_category: "ROOF SIDE",
  top_position: 17,
  bottom_position: 0,
  right_position: 0,
  left_position: 54,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 10,
  left_padding: 9,
 },
 {
  zone: 31,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "BACK DOOR INNER",
  top_position: 7,
  bottom_position: 0,
  right_position: 0,
  left_position: 34,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 18,
  left_padding: 16,
 },
 {
  zone: 32,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "BACK DOOR INNER",
  top_position: 50,
  bottom_position: 0,
  right_position: 0,
  left_position: 35,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 33,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "BACK DOOR INNER",
  top_position: 50,
  bottom_position: 0,
  right_position: 0,
  left_position: 51,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 9,
  left_padding: 8,
 },
 {
  zone: 34,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "BACK DOOR OUTER",
  top_position: 3,
  bottom_position: 0,
  right_position: 0,
  left_position: 33,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 18,
  left_padding: 15,
 },
 {
  zone: 35,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "BACK DOOR OUTER",
  top_position: 50,
  bottom_position: 0,
  right_position: 0,
  left_position: 29,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 9,
  left_padding: 9,
 },
 {
  zone: 36,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "BACK DOOR OUTER",
  top_position: 50,
  bottom_position: 0,
  right_position: 0,
  left_position: 49,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 9,
  left_padding: 9,
 },
 {
  zone: 37,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "FENDER",
  top_position: 33,
  bottom_position: 0,
  right_position: 0,
  left_position: 29,
  width: 5,
  top_padding: 7,
  bottom_padding: 10,
  right_padding: 7,
  left_padding: 8,
 },
 {
  zone: 39,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "FENDER",
  top_position: 6,
  bottom_position: 0,
  right_position: 0,
  left_position: 58,
  width: 5,
  top_padding: 7,
  bottom_padding: 10,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 40,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "FENDER",
  top_position: 51,
  bottom_position: 0,
  right_position: 0,
  left_position: 58,
  width: 5,
  top_padding: 7,
  bottom_padding: 9,
  right_padding: 7,
  left_padding: 5,
 },
 {
  zone: 41,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 41,
  bottom_position: 0,
  right_position: 0,
  left_position: 33,
  width: 5,
  top_padding: 7,
  bottom_padding: 11,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 42,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 42,
  bottom_position: 0,
  right_position: 0,
  left_position: 49,
  width: 5,
  top_padding: 7,
  bottom_padding: 11,
  right_padding: 5,
  left_padding: 10,
 },
 {
  zone: 43,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 11,
  bottom_position: 0,
  right_position: 0,
  left_position: 31,
  width: 5,
  top_padding: 4,
  bottom_padding: 7,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 44,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 22,
  bottom_position: 0,
  right_position: 0,
  left_position: 53,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 45,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 5,
  bottom_position: 0,
  right_position: 0,
  left_position: 41,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 6,
  left_padding: 6,
 },
 {
  zone: 46,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR OUTER",
  top_position: 41,
  bottom_position: 0,
  right_position: 0,
  left_position: 34,
  width: 5,
  top_padding: 9,
  bottom_padding: 11,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 47,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR OUTER",
  top_position: 41,
  bottom_position: 0,
  right_position: 0,
  left_position: 50,
  width: 5,
  top_padding: 9,
  bottom_padding: 11,
  right_padding: 7,
  left_padding: 7,
 },
 {
  zone: 48,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR OUTER",
  top_position: 13,
  bottom_position: 0,
  right_position: 0,
  left_position: 36,
  width: 5,
  top_padding: 4,
  bottom_padding: 7,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 49,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR OUTER",
  top_position: 4,
  bottom_position: 0,
  right_position: 0,
  left_position: 57,
  width: 5,
  top_padding: 5,
  bottom_padding: 9,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 50,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR OUTER",
  top_position: 1,
  bottom_position: 0,
  right_position: 0,
  left_position: 46,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 6,
 },
 {
  zone: 51,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "REAR DOOR INNER",
  top_position: 36,
  bottom_position: 0,
  right_position: 0,
  left_position: 35,
  width: 5,
  top_padding: 10,
  bottom_padding: 12,
  right_padding: 9,
  left_padding: 7,
 },
 {
  zone: 52,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "REAR DOOR INNER",
  top_position: 36,
  bottom_position: 0,
  right_position: 0,
  left_position: 51,
  width: 5,
  top_padding: 10,
  bottom_padding: 12,
  right_padding: 7,
  left_padding: 5,
 },
 {
  zone: 53,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "REAR DOOR INNER",
  top_position: 2,
  bottom_position: 0,
  right_position: 0,
  left_position: 37,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 3,
  left_padding: 3,
 },
 {
  zone: 54,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "REAR DOOR INNER",
  top_position: 1,
  bottom_position: 0,
  right_position: 0,
  left_position: 56,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 3,
  left_padding: 3,
 },
 {
  zone: 55,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "REAR DOOR INNER",
  top_position: 3,
  bottom_position: 0,
  right_position: 0,
  left_position: 43,
  width: 5,
  top_padding: 1,
  bottom_padding: 4,
  right_padding: 7,
  left_padding: 6,
 },
 {
  zone: 56,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "REAR DOOR OUTER",
  top_position: 37,
  bottom_position: 0,
  right_position: 0,
  left_position: 36,
  width: 5,
  top_padding: 9,
  bottom_padding: 13,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 57,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "REAR DOOR OUTER",
  top_position: 37,
  bottom_position: 0,
  right_position: 0,
  left_position: 52,
  width: 5,
  top_padding: 9,
  bottom_padding: 13,
  right_padding: 6,
  left_padding: 7,
 },
 {
  zone: 58,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "REAR DOOR OUTER",
  top_position: 2,
  bottom_position: 0,
  right_position: 0,
  left_position: 37,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 3,
  left_padding: 3,
 },
 {
  zone: 59,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "REAR DOOR OUTER",
  top_position: 2,
  bottom_position: 0,
  right_position: 0,
  left_position: 57,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 3,
  left_padding: 3,
 },
 {
  zone: 60,
  category: "LH SHELL BODY MAIN-LINE",
  sub_category: "REAR DOOR OUTER",
  top_position: 4,
  bottom_position: 0,
  right_position: 0,
  left_position: 43,
  width: 5,
  top_padding: 1,
  bottom_padding: 4,
  right_padding: 6,
  left_padding: 8,
 },
 {
  zone: 61,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "BACK DOOR INNER",
  top_position: 7,
  bottom_position: 0,
  right_position: 0,
  left_position: 34,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 18,
  left_padding: 16,
 },
 {
  zone: 62,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "BACK DOOR INNER",
  top_position: 50,
  bottom_position: 0,
  right_position: 0,
  left_position: 35,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 63,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "BACK DOOR INNER",
  top_position: 50,
  bottom_position: 0,
  right_position: 0,
  left_position: 51,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 9,
  left_padding: 8,
 },
 {
  zone: 64,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "BACK DOOR OUTER",
  top_position: 3,
  bottom_position: 0,
  right_position: 0,
  left_position: 33,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 18,
  left_padding: 15,
 },
 {
  zone: 65,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "BACK DOOR OUTER",
  top_position: 50,
  bottom_position: 0,
  right_position: 0,
  left_position: 29,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 9,
  left_padding: 9,
 },
 {
  zone: 66,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "BACK DOOR OUTER",
  top_position: 50,
  bottom_position: 0,
  right_position: 0,
  left_position: 49,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 9,
  left_padding: 9,
 },
 {
  zone: 67,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 41,
  bottom_position: 0,
  right_position: 0,
  left_position: 33,
  width: 5,
  top_padding: 7,
  bottom_padding: 11,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 68,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 42,
  bottom_position: 0,
  right_position: 0,
  left_position: 49,
  width: 5,
  top_padding: 7,
  bottom_padding: 11,
  right_padding: 5,
  left_padding: 10,
 },
 {
  zone: 71,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 5,
  bottom_position: 0,
  right_position: 0,
  left_position: 41,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 6,
  left_padding: 6,
 },
 {
  zone: 69,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 11,
  bottom_position: 0,
  right_position: 0,
  left_position: 31,
  width: 5,
  top_padding: 4,
  bottom_padding: 7,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 70,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 22,
  bottom_position: 0,
  right_position: 0,
  left_position: 53,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 72,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR OUTER",
  top_position: 41,
  bottom_position: 0,
  right_position: 0,
  left_position: 34,
  width: 5,
  top_padding: 9,
  bottom_padding: 11,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 73,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR OUTER",
  top_position: 41,
  bottom_position: 0,
  right_position: 0,
  left_position: 50,
  width: 5,
  top_padding: 9,
  bottom_padding: 11,
  right_padding: 7,
  left_padding: 7,
 },
 {
  zone: 74,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR OUTER",
  top_position: 13,
  bottom_position: 0,
  right_position: 0,
  left_position: 36,
  width: 5,
  top_padding: 4,
  bottom_padding: 7,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 75,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR OUTER",
  top_position: 4,
  bottom_position: 0,
  right_position: 0,
  left_position: 57,
  width: 5,
  top_padding: 5,
  bottom_padding: 9,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 76,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR OUTER",
  top_position: 1,
  bottom_position: 0,
  right_position: 0,
  left_position: 46,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 6,
 },
 {
  zone: 77,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "REAR DOOR INNER",
  top_position: 36,
  bottom_position: 0,
  right_position: 0,
  left_position: 35,
  width: 5,
  top_padding: 10,
  bottom_padding: 12,
  right_padding: 9,
  left_padding: 7,
 },
 {
  zone: 78,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "REAR DOOR INNER",
  top_position: 36,
  bottom_position: 0,
  right_position: 0,
  left_position: 51,
  width: 5,
  top_padding: 10,
  bottom_padding: 12,
  right_padding: 7,
  left_padding: 5,
 },
 {
  zone: 79,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "REAR DOOR INNER",
  top_position: 2,
  bottom_position: 0,
  right_position: 0,
  left_position: 37,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 3,
  left_padding: 3,
 },
 {
  zone: 80,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "REAR DOOR INNER",
  top_position: 1,
  bottom_position: 0,
  right_position: 0,
  left_position: 56,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 3,
  left_padding: 3,
 },
 {
  zone: 81,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "REAR DOOR INNER",
  top_position: 3,
  bottom_position: 0,
  right_position: 0,
  left_position: 43,
  width: 5,
  top_padding: 1,
  bottom_padding: 4,
  right_padding: 7,
  left_padding: 6,
 },
 {
  zone: 82,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "REAR DOOR OUTER",
  top_position: 37,
  bottom_position: 0,
  right_position: 0,
  left_position: 36,
  width: 5,
  top_padding: 9,
  bottom_padding: 13,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 83,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "REAR DOOR OUTER",
  top_position: 37,
  bottom_position: 0,
  right_position: 0,
  left_position: 52,
  width: 5,
  top_padding: 9,
  bottom_padding: 13,
  right_padding: 6,
  left_padding: 7,
 },
 {
  zone: 84,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "REAR DOOR OUTER",
  top_position: 2,
  bottom_position: 0,
  right_position: 0,
  left_position: 37,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 3,
  left_padding: 3,
 },
 {
  zone: 85,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "REAR DOOR OUTER",
  top_position: 2,
  bottom_position: 0,
  right_position: 0,
  left_position: 57,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 3,
  left_padding: 3,
 },
 {
  zone: 86,
  category: "LH SHELL BODY SUB-LINE",
  sub_category: "REAR DOOR OUTER",
  top_position: 4,
  bottom_position: 0,
  right_position: 0,
  left_position: 43,
  width: 5,
  top_padding: 1,
  bottom_padding: 4,
  right_padding: 6,
  left_padding: 8,
 },
 {
  zone: 87,
  category: "LH SIDE MEMBER",
  sub_category: "A-PILLAR",
  top_position: 20,
  bottom_position: 0,
  right_position: 0,
  left_position: 29,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 89,
  category: "LH SIDE MEMBER",
  sub_category: "A-PILLAR",
  top_position: 39,
  bottom_position: 0,
  right_position: 0,
  left_position: 26,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 90,
  category: "LH SIDE MEMBER",
  sub_category: "A-PILLAR",
  top_position: 58,
  bottom_position: 0,
  right_position: 0,
  left_position: 26,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 88,
  category: "LH SIDE MEMBER",
  sub_category: "A-PILLAR",
  top_position: 19,
  bottom_position: 0,
  right_position: 0,
  left_position: 39,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 91,
  category: "LH SIDE MEMBER",
  sub_category: "B-PILLAR",
  top_position: 21,
  bottom_position: 0,
  right_position: 0,
  left_position: 42,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 93,
  category: "LH SIDE MEMBER",
  sub_category: "B-PILLAR",
  top_position: 59,
  bottom_position: 0,
  right_position: 0,
  left_position: 42,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 92,
  category: "LH SIDE MEMBER",
  sub_category: "B-PILLAR",
  top_position: 41,
  bottom_position: 0,
  right_position: 0,
  left_position: 42,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 94,
  category: "LH SIDE MEMBER",
  sub_category: "C-PILLAR",
  top_position: 26,
  bottom_position: 0,
  right_position: 0,
  left_position: 55,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 95,
  category: "LH SIDE MEMBER",
  sub_category: "C-PILLAR",
  top_position: 46,
  bottom_position: 0,
  right_position: 0,
  left_position: 55,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 96,
  category: "LH SIDE MEMBER",
  sub_category: "BACK DOOR OPENING",
  top_position: 0,
  bottom_position: 0,
  right_position: 0,
  left_position: 31,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 10,
  left_padding: 10,
 },
 {
  zone: 97,
  category: "LH SIDE MEMBER",
  sub_category: "BACK DOOR OPENING",
  top_position: 0,
  bottom_position: 0,
  right_position: 0,
  left_position: 51,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 10,
  left_padding: 10,
 },
 {
  zone: 99,
  category: "LH SIDE MEMBER",
  sub_category: "BACK DOOR OPENING",
  top_position: 19,
  bottom_position: 0,
  right_position: 0,
  left_position: 66,
  width: 5,
  top_padding: 10,
  bottom_padding: 15,
  right_padding: 6,
  left_padding: 6,
 },
 {
  zone: 98,
  category: "LH SIDE MEMBER",
  sub_category: "BACK DOOR OPENING",
  top_position: 19,
  bottom_position: 0,
  right_position: 0,
  left_position: 23,
  width: 5,
  top_padding: 10,
  bottom_padding: 15,
  right_padding: 7,
  left_padding: 6,
 },
 {
  zone: 100,
  category: "LH SIDE MEMBER",
  sub_category: "BACK DOOR OPENING",
  top_position: 71,
  bottom_position: 0,
  right_position: 0,
  left_position: 36,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 15,
  left_padding: 15,
 },
 {
  zone: 101,
  category: "LH SIDE MEMBER",
  sub_category: "FRONT DOOR OPENING",
  top_position: 18,
  bottom_position: 0,
  right_position: 0,
  left_position: 35,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 102,
  category: "LH SIDE MEMBER",
  sub_category: "FRONT DOOR OPENING",
  top_position: 38,
  bottom_position: 0,
  right_position: 0,
  left_position: 26,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 103,
  category: "LH SIDE MEMBER",
  sub_category: "FRONT DOOR OPENING",
  top_position: 60,
  bottom_position: 0,
  right_position: 0,
  left_position: 29,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 104,
  category: "LH SIDE MEMBER",
  sub_category: "FRONT DOOR OPENING",
  top_position: 38,
  bottom_position: 0,
  right_position: 0,
  left_position: 41,
  width: 5,
  top_padding: 6,
  bottom_padding: 9,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 105,
  category: "LH SIDE MEMBER",
  sub_category: "QUARTER",
  top_position: 18,
  bottom_position: 0,
  right_position: 0,
  left_position: 53,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 107,
  category: "LH SIDE MEMBER",
  sub_category: "QUARTER",
  top_position: 32,
  bottom_position: 0,
  right_position: 0,
  left_position: 69,
  width: 5,
  top_padding: 6,
  bottom_padding: 9,
  right_padding: 4,
  left_padding: 3,
 },
 {
  zone: 106,
  category: "LH SIDE MEMBER",
  sub_category: "QUARTER",
  top_position: 39,
  bottom_position: 0,
  right_position: 0,
  left_position: 54,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 108,
  category: "LH SIDE MEMBER",
  sub_category: "REAR DOOR OPENING",
  top_position: 15,
  bottom_position: 0,
  right_position: 0,
  left_position: 48,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 110,
  category: "LH SIDE MEMBER",
  sub_category: "REAR DOOR OPENING",
  top_position: 33,
  bottom_position: 0,
  right_position: 0,
  left_position: 56,
  width: 5,
  top_padding: 7,
  bottom_padding: 10,
  right_padding: 3,
  left_padding: 3,
 },
 {
  zone: 109,
  category: "LH SIDE MEMBER",
  sub_category: "REAR DOOR OPENING",
  top_position: 29,
  bottom_position: 0,
  right_position: 0,
  left_position: 41,
  width: 5,
  top_padding: 8,
  bottom_padding: 11,
  right_padding: 4,
  left_padding: 4,
 },
 {
  zone: 111,
  category: "LH SIDE MEMBER",
  sub_category: "ROCKER PANEL SIDE",
  top_position: 64,
  bottom_position: 0,
  right_position: 0,
  left_position: 29,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 112,
  category: "LH SIDE MEMBER",
  sub_category: "ROCKER PANEL SIDE",
  top_position: 64,
  bottom_position: 0,
  right_position: 0,
  left_position: 45,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 7,
  left_padding: 7,
 },
 {
  zone: 113,
  category: "LH SIDE MEMBER",
  sub_category: "ROOF SIDE",
  top_position: 17,
  bottom_position: 0,
  right_position: 0,
  left_position: 34,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 10,
  left_padding: 10,
 },
 {
  zone: 114,
  category: "LH SIDE MEMBER",
  sub_category: "ROOF SIDE",
  top_position: 17,
  bottom_position: 0,
  right_position: 0,
  left_position: 54,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 10,
  left_padding: 9,
 },
 {
  zone: 115,
  category: "RH MAIN BODY",
  sub_category: "A-PILLAR",
  top_position: 14,
  bottom_position: 0,
  right_position: 0,
  left_position: 53,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 116,
  category: "RH MAIN BODY",
  sub_category: "A-PILLAR",
  top_position: 30,
  bottom_position: 0,
  right_position: 0,
  left_position: 63,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 117,
  category: "RH MAIN BODY",
  sub_category: "A-PILLAR",
  top_position: 49,
  bottom_position: 0,
  right_position: 0,
  left_position: 63,
  width: 5,
  top_padding: 4,
  bottom_padding: 7,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 118,
  category: "RH MAIN BODY",
  sub_category: "B-PILLAR",
  top_position: 21,
  bottom_position: 0,
  right_position: 0,
  left_position: 48,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 119,
  category: "RH MAIN BODY",
  sub_category: "B-PILLAR",
  top_position: 40,
  bottom_position: 0,
  right_position: 0,
  left_position: 48,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 120,
  category: "RH MAIN BODY",
  sub_category: "B-PILLAR",
  top_position: 59,
  bottom_position: 0,
  right_position: 0,
  left_position: 48,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 121,
  category: "RH MAIN BODY",
  sub_category: "BACK DOOR OPENING",
  top_position: 1,
  bottom_position: 0,
  right_position: 0,
  left_position: 30,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 12,
  left_padding: 10,
 },
 {
  zone: 122,
  category: "RH MAIN BODY",
  sub_category: "BACK DOOR OPENING",
  top_position: 1,
  bottom_position: 0,
  right_position: 0,
  left_position: 52,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 11,
  left_padding: 9,
 },
 {
  zone: 123,
  category: "RH MAIN BODY",
  sub_category: "BACK DOOR OPENING",
  top_position: 20,
  bottom_position: 0,
  right_position: 0,
  left_position: 23,
  width: 5,
  top_padding: 10,
  bottom_padding: 15,
  right_padding: 6,
  left_padding: 6,
 },
 {
  zone: 124,
  category: "RH MAIN BODY",
  sub_category: "BACK DOOR OPENING",
  top_position: 20,
  bottom_position: 0,
  right_position: 0,
  left_position: 67,
  width: 5,
  top_padding: 11,
  bottom_padding: 14,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 125,
  category: "RH MAIN BODY",
  sub_category: "BACK DOOR OPENING",
  top_position: 70,
  bottom_position: 0,
  right_position: 0,
  left_position: 35,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 16,
  left_padding: 16,
 },
 {
  zone: 126,
  category: "RH MAIN BODY",
  sub_category: "C-PILLAR",
  top_position: 22,
  bottom_position: 0,
  right_position: 0,
  left_position: 35,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 127,
  category: "RH MAIN BODY",
  sub_category: "C-PILLAR",
  top_position: 41,
  bottom_position: 0,
  right_position: 0,
  left_position: 35,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 128,
  category: "RH MAIN BODY",
  sub_category: "C-PILLAR",
  top_position: 60,
  bottom_position: 0,
  right_position: 0,
  left_position: 38,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 129,
  category: "RH MAIN BODY",
  sub_category: "COWL",
  top_position: 9,
  bottom_position: 0,
  right_position: 0,
  left_position: 25,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 12,
  left_padding: 12,
 },
 {
  zone: 130,
  category: "RH MAIN BODY",
  sub_category: "COWL",
  top_position: 9,
  bottom_position: 0,
  right_position: 0,
  left_position: 49,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 10,
  left_padding: 10,
 },
 {
  zone: 141,
  category: "RH MAIN BODY",
  sub_category: "REAR DOOR OPENING",
  top_position: 37,
  bottom_position: 0,
  right_position: 0,
  left_position: 36,
  width: 5,
  top_padding: 3,
  bottom_padding: 5,
  right_padding: 4,
  left_padding: 4,
 },
 {
  zone: 132,
  category: "RH MAIN BODY",
  sub_category: "FRONT DOOR OPENING",
  top_position: 30,
  bottom_position: 0,
  right_position: 0,
  left_position: 64,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 133,
  category: "RH MAIN BODY",
  sub_category: "FRONT DOOR OPENING",
  top_position: 49,
  bottom_position: 0,
  right_position: 0,
  left_position: 64,
  width: 5,
  top_padding: 4,
  bottom_padding: 7,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 134,
  category: "RH MAIN BODY",
  sub_category: "FRONT DOOR OPENING",
  top_position: 62,
  bottom_position: 0,
  right_position: 0,
  left_position: 48,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 135,
  category: "RH MAIN BODY",
  sub_category: "FRONT DOOR OPENING",
  top_position: 34,
  bottom_position: 0,
  right_position: 0,
  left_position: 47,
  width: 5,
  top_padding: 3,
  bottom_padding: 7,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 131,
  category: "RH MAIN BODY",
  sub_category: "FRONT DOOR OPENING",
  top_position: 15,
  bottom_position: 0,
  right_position: 0,
  left_position: 47,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 9,
  left_padding: 8,
 },
 {
  zone: 136,
  category: "RH MAIN BODY",
  sub_category: "QUARTER",
  top_position: 24,
  bottom_position: 0,
  right_position: 0,
  left_position: 29,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 6,
  left_padding: 6,
 },
 {
  zone: 137,
  category: "RH MAIN BODY",
  sub_category: "QUARTER",
  top_position: 43,
  bottom_position: 0,
  right_position: 0,
  left_position: 29,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 6,
  left_padding: 6,
 },
 {
  zone: 138,
  category: "RH MAIN BODY",
  sub_category: "REAR DOOR OPENING",
  top_position: 18,
  bottom_position: 0,
  right_position: 0,
  left_position: 42,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 139,
  category: "RH MAIN BODY",
  sub_category: "REAR DOOR OPENING",
  top_position: 37,
  bottom_position: 0,
  right_position: 0,
  left_position: 48,
  width: 5,
  top_padding: 6,
  bottom_padding: 9,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 140,
  category: "RH MAIN BODY",
  sub_category: "REAR DOOR OPENING",
  top_position: 59,
  bottom_position: 0,
  right_position: 0,
  left_position: 38,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 142,
  category: "RH MAIN BODY",
  sub_category: "ROCKER PANEL SIDE",
  top_position: 64,
  bottom_position: 0,
  right_position: 0,
  left_position: 39,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 143,
  category: "RH MAIN BODY",
  sub_category: "ROCKER PANEL SIDE",
  top_position: 64,
  bottom_position: 0,
  right_position: 0,
  left_position: 55,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 7,
  left_padding: 8,
 },
 {
  zone: 144,
  category: "RH MAIN BODY",
  sub_category: "ROOF SIDE",
  top_position: 18,
  bottom_position: 0,
  right_position: 0,
  left_position: 28,
  width: 5,
  top_padding: 1,
  bottom_padding: 4,
  right_padding: 10,
  left_padding: 9,
 },
 {
  zone: 145,
  category: "RH MAIN BODY",
  sub_category: "ROOF SIDE",
  top_position: 18,
  bottom_position: 0,
  right_position: 0,
  left_position: 47,
  width: 5,
  top_padding: 1,
  bottom_padding: 4,
  right_padding: 6,
  left_padding: 7,
 },
 {
  zone: 147,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "FENDER",
  top_position: 3,
  bottom_position: 0,
  right_position: 0,
  left_position: 30,
  width: 5,
  top_padding: 8,
  bottom_padding: 11,
  right_padding: 6,
  left_padding: 8,
 },
 {
  zone: 146,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "FENDER",
  top_position: 54,
  bottom_position: 0,
  right_position: 0,
  left_position: 29,
  width: 5,
  top_padding: 6,
  bottom_padding: 8,
  right_padding: 8,
  left_padding: 7,
 },
 {
  zone: 148,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "FENDER",
  top_position: 18,
  bottom_position: 0,
  right_position: 0,
  left_position: 44,
  width: 5,
  top_padding: 6,
  bottom_padding: 10,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 149,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "FENDER",
  top_position: 31,
  bottom_position: 0,
  right_position: 0,
  left_position: 54,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 10,
  left_padding: 9,
 },
 {
  zone: 150,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "FENDER",
  top_position: 50,
  bottom_position: 0,
  right_position: 0,
  left_position: 54,
  width: 5,
  top_padding: 4,
  bottom_padding: 7,
  right_padding: 9,
  left_padding: 9,
 },
 {
  zone: 151,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 41,
  bottom_position: 0,
  right_position: 0,
  left_position: 33,
  width: 5,
  top_padding: 7,
  bottom_padding: 11,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 152,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 42,
  bottom_position: 0,
  right_position: 0,
  left_position: 49,
  width: 5,
  top_padding: 7,
  bottom_padding: 11,
  right_padding: 5,
  left_padding: 10,
 },
 {
  zone: 153,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 10,
  bottom_position: 0,
  right_position: 0,
  left_position: 37,
  width: 5,
  top_padding: 4,
  bottom_padding: 7,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 155,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 3,
  bottom_position: 0,
  right_position: 0,
  left_position: 47,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 10,
  left_padding: 8,
 },
 {
  zone: 154,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 22,
  bottom_position: 0,
  right_position: 0,
  left_position: 58,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 156,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR OUTER",
  top_position: 41,
  bottom_position: 0,
  right_position: 0,
  left_position: 34,
  width: 5,
  top_padding: 9,
  bottom_padding: 11,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 157,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR OUTER",
  top_position: 41,
  bottom_position: 0,
  right_position: 0,
  left_position: 50,
  width: 5,
  top_padding: 9,
  bottom_padding: 11,
  right_padding: 7,
  left_padding: 7,
 },
 {
  zone: 159,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR OUTER",
  top_position: 4,
  bottom_position: 0,
  right_position: 0,
  left_position: 33,
  width: 5,
  top_padding: 5,
  bottom_padding: 9,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 158,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR OUTER",
  top_position: 13,
  bottom_position: 0,
  right_position: 0,
  left_position: 54,
  width: 5,
  top_padding: 4,
  bottom_padding: 7,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 160,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR OUTER",
  top_position: 2,
  bottom_position: 0,
  right_position: 0,
  left_position: 43,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 6,
 },
 {
  zone: 208,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "REAR DOOR OUTER",
  top_position: 36,
  bottom_position: 0,
  right_position: 0,
  left_position: 35,
  width: 5,
  top_padding: 10,
  bottom_padding: 12,
  right_padding: 9,
  left_padding: 7,
 },
 {
  zone: 210,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "REAR DOOR OUTER",
  top_position: 1,
  bottom_position: 0,
  right_position: 0,
  left_position: 56,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 3,
  left_padding: 3,
 },
 {
  zone: 162,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "HOOD SA INNER",
  top_position: 22,
  bottom_position: 0,
  right_position: 0,
  left_position: 44,
  width: 5,
  top_padding: 8,
  bottom_padding: 13,
  right_padding: 7,
  left_padding: 8,
 },
 {
  zone: 163,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "HOOD SA INNER",
  top_position: 17,
  bottom_position: 0,
  right_position: 0,
  left_position: 59,
  width: 5,
  top_padding: 9,
  bottom_padding: 13,
  right_padding: 6,
  left_padding: 6,
 },
 {
  zone: 161,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "HOOD SA INNER",
  top_position: 20,
  bottom_position: 0,
  right_position: 0,
  left_position: 30,
  width: 5,
  top_padding: 8,
  bottom_padding: 13,
  right_padding: 7,
  left_padding: 7,
 },
 {
  zone: 166,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "HOOD SA OUTER",
  top_position: 11,
  bottom_position: 0,
  right_position: 0,
  left_position: 25,
  width: 5,
  top_padding: 10,
  bottom_padding: 15,
  right_padding: 8,
  left_padding: 9,
 },
 {
  zone: 164,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "HOOD SA OUTER",
  top_position: 20,
  bottom_position: 0,
  right_position: 0,
  left_position: 42,
  width: 5,
  top_padding: 8,
  bottom_padding: 14,
  right_padding: 7,
  left_padding: 8,
 },
 {
  zone: 165,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "HOOD SA OUTER",
  top_position: 10,
  bottom_position: 0,
  right_position: 0,
  left_position: 57,
  width: 5,
  top_padding: 10,
  bottom_padding: 14,
  right_padding: 6,
  left_padding: 6,
 },
 {
  zone: 167,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "REAR DOOR OUTER",
  top_position: 36,
  bottom_position: 0,
  right_position: 0,
  left_position: 35,
  width: 5,
  top_padding: 10,
  bottom_padding: 12,
  right_padding: 9,
  left_padding: 7,
 },
 {
  zone: 168,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "REAR DOOR OUTER",
  top_position: 36,
  bottom_position: 0,
  right_position: 0,
  left_position: 51,
  width: 5,
  top_padding: 10,
  bottom_padding: 12,
  right_padding: 7,
  left_padding: 5,
 },
 {
  zone: 170,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "REAR DOOR OUTER",
  top_position: 1,
  bottom_position: 0,
  right_position: 0,
  left_position: 56,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 3,
  left_padding: 3,
 },
 {
  zone: 169,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "REAR DOOR OUTER",
  top_position: 2,
  bottom_position: 0,
  right_position: 0,
  left_position: 37,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 3,
  left_padding: 3,
 },
 {
  zone: 171,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "REAR DOOR OUTER",
  top_position: 3,
  bottom_position: 0,
  right_position: 0,
  left_position: 43,
  width: 5,
  top_padding: 1,
  bottom_padding: 4,
  right_padding: 7,
  left_padding: 6,
 },
 {
  zone: 172,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "REAR DOOR INNER",
  top_position: 36,
  bottom_position: 0,
  right_position: 0,
  left_position: 35,
  width: 5,
  top_padding: 10,
  bottom_padding: 12,
  right_padding: 9,
  left_padding: 7,
 },
 {
  zone: 174,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "REAR DOOR INNER",
  top_position: 2,
  bottom_position: 0,
  right_position: 0,
  left_position: 37,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 3,
  left_padding: 3,
 },
 {
  zone: 176,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "REAR DOOR INNER",
  top_position: 3,
  bottom_position: 0,
  right_position: 0,
  left_position: 43,
  width: 5,
  top_padding: 1,
  bottom_padding: 4,
  right_padding: 7,
  left_padding: 6,
 },
 {
  zone: 175,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "REAR DOOR INNER",
  top_position: 1,
  bottom_position: 0,
  right_position: 0,
  left_position: 56,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 3,
  left_padding: 3,
 },
 {
  zone: 173,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "REAR DOOR INNER",
  top_position: 36,
  bottom_position: 0,
  right_position: 0,
  left_position: 51,
  width: 5,
  top_padding: 10,
  bottom_padding: 12,
  right_padding: 7,
  left_padding: 5,
 },
 {
  zone: 177,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 41,
  bottom_position: 0,
  right_position: 0,
  left_position: 33,
  width: 5,
  top_padding: 7,
  bottom_padding: 11,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 179,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 10,
  bottom_position: 0,
  right_position: 0,
  left_position: 37,
  width: 5,
  top_padding: 4,
  bottom_padding: 7,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 180,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 3,
  bottom_position: 0,
  right_position: 0,
  left_position: 47,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 10,
  left_padding: 8,
 },
 {
  zone: 181,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 22,
  bottom_position: 0,
  right_position: 0,
  left_position: 58,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 178,
  category: "RH SHELL BODY MAIN-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 42,
  bottom_position: 0,
  right_position: 0,
  left_position: 49,
  width: 5,
  top_padding: 7,
  bottom_padding: 11,
  right_padding: 5,
  left_padding: 10,
 },
 {
  zone: 182,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 41,
  bottom_position: 0,
  right_position: 0,
  left_position: 33,
  width: 5,
  top_padding: 7,
  bottom_padding: 11,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 183,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 42,
  bottom_position: 0,
  right_position: 0,
  left_position: 49,
  width: 5,
  top_padding: 7,
  bottom_padding: 11,
  right_padding: 5,
  left_padding: 10,
 },
 {
  zone: 188,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 10,
  bottom_position: 0,
  right_position: 0,
  left_position: 37,
  width: 5,
  top_padding: 4,
  bottom_padding: 7,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 186,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 22,
  bottom_position: 0,
  right_position: 0,
  left_position: 58,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 184,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 10,
  bottom_position: 0,
  right_position: 0,
  left_position: 37,
  width: 5,
  top_padding: 4,
  bottom_padding: 7,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 185,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 3,
  bottom_position: 0,
  right_position: 0,
  left_position: 47,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 10,
  left_padding: 8,
 },
 {
  zone: 187,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 41,
  bottom_position: 0,
  right_position: 0,
  left_position: 33,
  width: 5,
  top_padding: 7,
  bottom_padding: 11,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 190,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 22,
  bottom_position: 0,
  right_position: 0,
  left_position: 58,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 189,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 3,
  bottom_position: 0,
  right_position: 0,
  left_position: 47,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 10,
  left_padding: 8,
 },
 {
  zone: 191,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR INNER",
  top_position: 42,
  bottom_position: 0,
  right_position: 0,
  left_position: 49,
  width: 5,
  top_padding: 7,
  bottom_padding: 11,
  right_padding: 5,
  left_padding: 10,
 },
 {
  zone: 192,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR OUTER",
  top_position: 41,
  bottom_position: 0,
  right_position: 0,
  left_position: 34,
  width: 5,
  top_padding: 9,
  bottom_padding: 11,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 194,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR OUTER",
  top_position: 4,
  bottom_position: 0,
  right_position: 0,
  left_position: 33,
  width: 5,
  top_padding: 5,
  bottom_padding: 9,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 196,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR OUTER",
  top_position: 2,
  bottom_position: 0,
  right_position: 0,
  left_position: 43,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 6,
 },
 {
  zone: 195,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR OUTER",
  top_position: 13,
  bottom_position: 0,
  right_position: 0,
  left_position: 54,
  width: 5,
  top_padding: 4,
  bottom_padding: 7,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 193,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "FRONT DOOR OUTER",
  top_position: 41,
  bottom_position: 0,
  right_position: 0,
  left_position: 50,
  width: 5,
  top_padding: 9,
  bottom_padding: 11,
  right_padding: 7,
  left_padding: 7,
 },
 {
  zone: 199,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "HOOD SA INNER",
  top_position: 20,
  bottom_position: 0,
  right_position: 0,
  left_position: 27,
  width: 5,
  top_padding: 11,
  bottom_padding: 13,
  right_padding: 7,
  left_padding: 9,
 },
 {
  zone: 197,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "HOOD SA INNER",
  top_position: 22,
  bottom_position: 0,
  right_position: 0,
  left_position: 43,
  width: 5,
  top_padding: 11,
  bottom_padding: 14,
  right_padding: 8,
  left_padding: 9,
 },
 {
  zone: 198,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "HOOD SA INNER",
  top_position: 18,
  bottom_position: 0,
  right_position: 0,
  left_position: 60,
  width: 5,
  top_padding: 12,
  bottom_padding: 14,
  right_padding: 7,
  left_padding: 8,
 },
 {
  zone: 200,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "HOOD SA OUTER",
  top_position: 11,
  bottom_position: 0,
  right_position: 0,
  left_position: 27,
  width: 5,
  top_padding: 10,
  bottom_padding: 18,
  right_padding: 8,
  left_padding: 9,
 },
 {
  zone: 201,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "HOOD SA OUTER",
  top_position: 20,
  bottom_position: 0,
  right_position: 0,
  left_position: 44,
  width: 5,
  top_padding: 10,
  bottom_padding: 16,
  right_padding: 7,
  left_padding: 8,
 },
 {
  zone: 202,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "HOOD SA OUTER",
  top_position: 13,
  bottom_position: 0,
  right_position: 0,
  left_position: 59,
  width: 5,
  top_padding: 12,
  bottom_padding: 15,
  right_padding: 8,
  left_padding: 9,
 },
 {
  zone: 203,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "REAR DOOR INNER",
  top_position: 36,
  bottom_position: 0,
  right_position: 0,
  left_position: 35,
  width: 5,
  top_padding: 10,
  bottom_padding: 12,
  right_padding: 9,
  left_padding: 7,
 },
 {
  zone: 204,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "REAR DOOR INNER",
  top_position: 2,
  bottom_position: 0,
  right_position: 0,
  left_position: 37,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 3,
  left_padding: 3,
 },
 {
  zone: 206,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "REAR DOOR INNER",
  top_position: 1,
  bottom_position: 0,
  right_position: 0,
  left_position: 56,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 3,
  left_padding: 3,
 },
 {
  zone: 205,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "REAR DOOR INNER",
  top_position: 3,
  bottom_position: 0,
  right_position: 0,
  left_position: 43,
  width: 5,
  top_padding: 1,
  bottom_padding: 4,
  right_padding: 7,
  left_padding: 6,
 },
 {
  zone: 207,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "REAR DOOR INNER",
  top_position: 36,
  bottom_position: 0,
  right_position: 0,
  left_position: 51,
  width: 5,
  top_padding: 10,
  bottom_padding: 12,
  right_padding: 7,
  left_padding: 5,
 },
 {
  zone: 209,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "REAR DOOR OUTER",
  top_position: 36,
  bottom_position: 0,
  right_position: 0,
  left_position: 51,
  width: 5,
  top_padding: 10,
  bottom_padding: 12,
  right_padding: 7,
  left_padding: 5,
 },
 {
  zone: 211,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "REAR DOOR OUTER",
  top_position: 2,
  bottom_position: 0,
  right_position: 0,
  left_position: 37,
  width: 5,
  top_padding: 5,
  bottom_padding: 8,
  right_padding: 3,
  left_padding: 3,
 },
 {
  zone: 212,
  category: "RH SHELL BODY SUB-LINE",
  sub_category: "REAR DOOR OUTER",
  top_position: 3,
  bottom_position: 0,
  right_position: 0,
  left_position: 43,
  width: 5,
  top_padding: 1,
  bottom_padding: 4,
  right_padding: 7,
  left_padding: 6,
 },
 {
  zone: 213,
  category: "RH SIDE MEMBER",
  sub_category: "A-PILLAR",
  top_position: 14,
  bottom_position: 0,
  right_position: 0,
  left_position: 53,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 214,
  category: "RH SIDE MEMBER",
  sub_category: "A-PILLAR",
  top_position: 30,
  bottom_position: 0,
  right_position: 0,
  left_position: 63,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 215,
  category: "RH SIDE MEMBER",
  sub_category: "A-PILLAR",
  top_position: 49,
  bottom_position: 0,
  right_position: 0,
  left_position: 63,
  width: 5,
  top_padding: 4,
  bottom_padding: 7,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 216,
  category: "RH SIDE MEMBER",
  sub_category: "B-PILLAR",
  top_position: 21,
  bottom_position: 0,
  right_position: 0,
  left_position: 48,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 217,
  category: "RH SIDE MEMBER",
  sub_category: "B-PILLAR",
  top_position: 40,
  bottom_position: 0,
  right_position: 0,
  left_position: 48,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 218,
  category: "RH SIDE MEMBER",
  sub_category: "B-PILLAR",
  top_position: 59,
  bottom_position: 0,
  right_position: 0,
  left_position: 48,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 219,
  category: "RH SIDE MEMBER",
  sub_category: "C-PILLAR",
  top_position: 22,
  bottom_position: 0,
  right_position: 0,
  left_position: 35,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 220,
  category: "RH SIDE MEMBER",
  sub_category: "C-PILLAR",
  top_position: 41,
  bottom_position: 0,
  right_position: 0,
  left_position: 35,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 221,
  category: "RH SIDE MEMBER",
  sub_category: "C-PILLAR",
  top_position: 60,
  bottom_position: 0,
  right_position: 0,
  left_position: 38,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 222,
  category: "RH SIDE MEMBER",
  sub_category: "BACK DOOR OPENING",
  top_position: 1,
  bottom_position: 0,
  right_position: 0,
  left_position: 30,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 12,
  left_padding: 10,
 },
 {
  zone: 223,
  category: "RH SIDE MEMBER",
  sub_category: "BACK DOOR OPENING",
  top_position: 1,
  bottom_position: 0,
  right_position: 0,
  left_position: 52,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 11,
  left_padding: 9,
 },
 {
  zone: 224,
  category: "RH SIDE MEMBER",
  sub_category: "BACK DOOR OPENING",
  top_position: 20,
  bottom_position: 0,
  right_position: 0,
  left_position: 23,
  width: 5,
  top_padding: 10,
  bottom_padding: 15,
  right_padding: 6,
  left_padding: 6,
 },
 {
  zone: 225,
  category: "RH SIDE MEMBER",
  sub_category: "BACK DOOR OPENING",
  top_position: 20,
  bottom_position: 0,
  right_position: 0,
  left_position: 67,
  width: 5,
  top_padding: 11,
  bottom_padding: 14,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 226,
  category: "RH SIDE MEMBER",
  sub_category: "BACK DOOR OPENING",
  top_position: 70,
  bottom_position: 0,
  right_position: 0,
  left_position: 35,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 16,
  left_padding: 16,
 },
 {
  zone: 227,
  category: "RH SIDE MEMBER",
  sub_category: "FRONT DOOR OPENING",
  top_position: 30,
  bottom_position: 0,
  right_position: 0,
  left_position: 64,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 228,
  category: "RH SIDE MEMBER",
  sub_category: "FRONT DOOR OPENING",
  top_position: 49,
  bottom_position: 0,
  right_position: 0,
  left_position: 64,
  width: 5,
  top_padding: 4,
  bottom_padding: 7,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 230,
  category: "RH SIDE MEMBER",
  sub_category: "FRONT DOOR OPENING",
  top_position: 34,
  bottom_position: 0,
  right_position: 0,
  left_position: 47,
  width: 5,
  top_padding: 3,
  bottom_padding: 7,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 231,
  category: "RH SIDE MEMBER",
  sub_category: "FRONT DOOR OPENING",
  top_position: 15,
  bottom_position: 0,
  right_position: 0,
  left_position: 47,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 9,
  left_padding: 8,
 },
 {
  zone: 229,
  category: "RH SIDE MEMBER",
  sub_category: "FRONT DOOR OPENING",
  top_position: 62,
  bottom_position: 0,
  right_position: 0,
  left_position: 48,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 232,
  category: "RH SIDE MEMBER",
  sub_category: "QUARTER",
  top_position: 24,
  bottom_position: 0,
  right_position: 0,
  left_position: 29,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 6,
  left_padding: 6,
 },
 {
  zone: 233,
  category: "RH SIDE MEMBER",
  sub_category: "QUARTER",
  top_position: 43,
  bottom_position: 0,
  right_position: 0,
  left_position: 29,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 6,
  left_padding: 6,
 },
 {
  zone: 234,
  category: "RH SIDE MEMBER",
  sub_category: "REAR DOOR OPENING",
  top_position: 37,
  bottom_position: 0,
  right_position: 0,
  left_position: 36,
  width: 5,
  top_padding: 3,
  bottom_padding: 5,
  right_padding: 4,
  left_padding: 4,
 },
 {
  zone: 235,
  category: "RH SIDE MEMBER",
  sub_category: "REAR DOOR OPENING",
  top_position: 18,
  bottom_position: 0,
  right_position: 0,
  left_position: 42,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 236,
  category: "RH SIDE MEMBER",
  sub_category: "REAR DOOR OPENING",
  top_position: 37,
  bottom_position: 0,
  right_position: 0,
  left_position: 48,
  width: 5,
  top_padding: 6,
  bottom_padding: 9,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 237,
  category: "RH SIDE MEMBER",
  sub_category: "REAR DOOR OPENING",
  top_position: 59,
  bottom_position: 0,
  right_position: 0,
  left_position: 38,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 5,
  left_padding: 5,
 },
 {
  zone: 238,
  category: "RH SIDE MEMBER",
  sub_category: "ROCKER PANEL SIDE",
  top_position: 64,
  bottom_position: 0,
  right_position: 0,
  left_position: 39,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 8,
  left_padding: 8,
 },
 {
  zone: 239,
  category: "RH SIDE MEMBER",
  sub_category: "ROCKER PANEL SIDE",
  top_position: 64,
  bottom_position: 0,
  right_position: 0,
  left_position: 55,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 7,
  left_padding: 8,
 },
 {
  zone: 240,
  category: "RH SIDE MEMBER",
  sub_category: "ROOF SIDE",
  top_position: 18,
  bottom_position: 0,
  right_position: 0,
  left_position: 28,
  width: 5,
  top_padding: 1,
  bottom_padding: 4,
  right_padding: 10,
  left_padding: 9,
 },
 {
  zone: 241,
  category: "RH SIDE MEMBER",
  sub_category: "ROOF SIDE",
  top_position: 18,
  bottom_position: 0,
  right_position: 0,
  left_position: 47,
  width: 5,
  top_padding: 1,
  bottom_padding: 4,
  right_padding: 6,
  left_padding: 7,
 },
 {
  zone: 242,
  category: "UNDER BODY",
  sub_category: "DASH INNER",
  top_position: 22,
  bottom_position: 0,
  right_position: 0,
  left_position: 26,
  width: 5,
  top_padding: 9,
  bottom_padding: 11,
  right_padding: 8,
  left_padding: 10,
 },
 {
  zone: 243,
  category: "UNDER BODY",
  sub_category: "DASH INNER",
  top_position: 20,
  bottom_position: 0,
  right_position: 0,
  left_position: 44,
  width: 5,
  top_padding: 9,
  bottom_padding: 11,
  right_padding: 8,
  left_padding: 9,
 },
 {
  zone: 244,
  category: "UNDER BODY",
  sub_category: "DASH INNER",
  top_position: 24,
  bottom_position: 0,
  right_position: 0,
  left_position: 61,
  width: 5,
  top_padding: 9,
  bottom_padding: 11,
  right_padding: 6,
  left_padding: 6,
 },
 {
  zone: 246,
  category: "UNDER BODY",
  sub_category: "RADIATOR SUPPORT",
  top_position: 14,
  bottom_position: 0,
  right_position: 0,
  left_position: 54,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 11,
  left_padding: 10,
 },
 {
  zone: 247,
  category: "UNDER BODY",
  sub_category: "RADIATOR SUPPORT",
  top_position: 36,
  bottom_position: 0,
  right_position: 0,
  left_position: 42,
  width: 5,
  top_padding: 9,
  bottom_padding: 13,
  right_padding: 8,
  left_padding: 9,
 },
 {
  zone: 248,
  category: "UNDER BODY",
  sub_category: "RADIATOR SUPPORT",
  top_position: 43,
  bottom_position: 0,
  right_position: 0,
  left_position: 25,
  width: 5,
  top_padding: 7,
  bottom_padding: 8,
  right_padding: 8,
  left_padding: 9,
 },
 {
  zone: 249,
  category: "UNDER BODY",
  sub_category: "RADIATOR SUPPORT",
  top_position: 72,
  bottom_position: 0,
  right_position: 0,
  left_position: 59,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 9,
  left_padding: 8,
 },
 {
  zone: 245,
  category: "UNDER BODY",
  sub_category: "RADIATOR SUPPORT",
  top_position: 15,
  bottom_position: 0,
  right_position: 0,
  left_position: 25,
  width: 5,
  top_padding: 2,
  bottom_padding: 5,
  right_padding: 17,
  left_padding: 11,
 },
 {
  zone: 250,
  category: "UNDER BODY",
  sub_category: "REAR FLOOR BOTTOM SIDE",
  top_position: 16,
  bottom_position: 0,
  right_position: 0,
  left_position: 25,
  width: 5,
  top_padding: 8,
  bottom_padding: 14,
  right_padding: 10,
  left_padding: 9,
 },
 {
  zone: 251,
  category: "UNDER BODY",
  sub_category: "REAR FLOOR BOTTOM SIDE",
  top_position: 13,
  bottom_position: 0,
  right_position: 0,
  left_position: 44,
  width: 5,
  top_padding: 9,
  bottom_padding: 14,
  right_padding: 9,
  left_padding: 9,
 },
 {
  zone: 252,
  category: "UNDER BODY",
  sub_category: "REAR FLOOR BOTTOM SIDE",
  top_position: 16,
  bottom_position: 0,
  right_position: 0,
  left_position: 62,
  width: 5,
  top_padding: 10,
  bottom_padding: 13,
  right_padding: 8,
  left_padding: 10,
 },
];
